### ISSUE TITLE
TLSPExecuteServerThread.RunServer should use asynchronous I/O

### ISSUE THREAD

**Issue by pyscripter** [rickard67/LSP-Pascal-Library#2]
Instead of the tight loop with Sleep TLSPExecuteServerThread.RunServer should be using [asynchronous I/O](https://learn.microsoft.com/en-us/windows/win32/FileIO/synchronous-and-asynchronous-i-o).

For a Delphi implementation, see https://github.com/project-jedi/jcl/blob/master/jcl/source/common/JclSysUtils.pas#L3007.

**Comment by rickard67** [comment]
What would be the benefits of using asynchronous I/O?

I can think of a few benefits of using synchronous I/O, like sending request in the correct order (a second request is not sent until the first has completed), it's faster than asynchronous I/O, pretty easy to understand and maintain...

**Comment by pyscripter** [comment]
> it's faster than asynchronous I/O

No it is not faster.  Quite the opposite. You are operating a tight loop with sleep(20) and then using Peek.
With asynchronous I/O you use the Windows wait functions.   Your thread is woken only if/when there is something to read.  Otherwise it does nothing.  Currently, if something comes up while you are sleeping there is going to be an extra delay.   

Only the reading is asynchronous.  Writing remains the same.   The order is not an issue.  You just read whatever comes first as you do now.

Asynchronous I/O is also quite easy to implement.

**Comment by pyscripter** [comment]
By the way your TCP/IP handling has the same issue.

Using the RTL HTTPClient in asynchronous mode is much better that using Indy.

**Comment by rickard67** [comment]
I finally peaked at the implementation you linked to and it does look like it's easy enough to implement.

Are you interested in implementing it yourself? It may take some time before I have the time to...

**Comment by pyscripter** [comment]
> Are you interested in implementing it yourself? It may take some time before I have the time to...

I may try when I get some free time.   No promises.   In my implementation I am using Jcl, but I suppose you do not want an extra dependence.

By the way what is the editor component in RJ-TextEd?

**Comment by rickard67** [comment]
:) I think you've asked this before. I wrote it myself from scratch and I simply call it RJMemo. It has grown over the years and can now handle both text, binaries (hex view) and function as a console with some simple shell highlighting. It does have some dependencies on other components though and was never intended as an open source project.

**Comment by pyscripter** [comment]
I am getting old and my memory fails me..
Looks good though!
Have you look at [pyscripter/synedit](https://github.com/pyscripter/SynEdit/issues?q=is%3Aissue%20state%3Aclosed%20label%3Aenhancement)?

Written almost from scratch:
-  DirectWrite rendering
-  Perfect unicode support (emojis, bidirectional text etc.)
-  multi-cursor/selection 
-  indicators like Scientilla
- and much more...

**Comment by rickard67** [comment]
I assume it's what you use in your "Python Integrated Development Environment". 
When I started on my own memo component there weren't many options. So I wrote my own.. Today, maybe I would have used SynEdit instead.

**Comment by pyscripter** [comment]
@rickard67 Forked your repo (https://github.com/pyscripter/LSP-Pascal-Library) and made quite substantial changes:

   *  Removed third-party dependencies
      - Replaced XSuperObject (which is very [slow](https://github.com/hydrobyte/TestJSON)) with System.JSON and System.JSONSerializers.  
      - Removed Indy dependency (was not working anyway). Used System.Net.Socket instead.
   *  Fixed warnings and hints
   *  Fixed numerous memory leaks
   *  Improvements to XLSPExecute
      - Asynchronous reading
      - Avoid calling Synchronize and Sleep
 *  Allow for Handling server responses with anonymous method handlers.
     The handler is executed in the main thread.  
     Example:
     ```pascal
       FLSPClient.SendRequest(lspCompletionItemResolve, ResolveParams,
       procedure(Json: TJSONObject)
       var
         Item: TLSPCompletionItem;
       begin
         if ResponseError(Json) then Exit;
         Item := TSerializer.Deserialize<TLSPCompletionItem>(Json.Values['result']);
         Memo1.Lines.Add(TSerializer.Serialize(item));
       end);
    ```   
 *  Added Synchronous requests (SendSyncRequest).
    SendSyncRequest blocks until the server responds or a timeout expires.
    The handler is executed in the Server thread.  
    Example:
    ```pascal
      var Item: TLSPCompletionItem;
      if FLSPClient.SendSyncRequest(lspCompletionItemResolve, ResolveParams,
      procedure(Json: TJSONObject)
      begin
        if ResponseError(Json) then Exit;
        Item := TSerializer.Deserialize<TLSPCompletionItem>(Json.Values['result']);
      end, 400) then
        Memo1.Lines.Add(TSerializer.Serialize(Item));
    ```
 * The code base was enormously streamlined.  (e.g. XSLPFunction down to 1400 from 7000+ lines)
 * Removed unnecessary aliases in XLSPTypes
 *  Refactored error handling in XLSP functions
 *  Separated the handling of requests, notifications and responses
 *  Unique request id passed to the request handlers

**TODO:** Update the Demo.

Tested with a couple of servers using stdio and sockets.   However only a limited part of the LSP spec has been tested.  
(publish and pull diagnostics, code completion, code completion resolve item and a few more).

If you like what I have done, I could submit a PR and we can collaborate moving forward.

**Comment by rickard67** [comment]
Thank you. I'll take a closer look at it this weekend. 

I'll update the demo and use it for testing... I will probably have to try it in RJ TextEd as well with some good language servers.

**Comment by pyscripter** [comment]
@rickard67 
Updated and tested the demo. Seems to work fine without memory leaks.

![Image](https://github.com/user-attachments/assets/19218525-2fc5-4657-bbe0-8b27d46490da)

Question:  The OnWorkspaceApplyEdit does not seem to get used.  Am I missing something?

Notes: 
-  In the options you need to provide the full path in the command line:
  ![Image](https://github.com/user-attachments/assets/c5219025-fc69-4c59-9011-3e519253a715)
  This is because I removed the call to SetCurrentDir in XLSPExecute.   I don't my application's current directory to change when I load an LSP server.  Of course I could save the old current directory and restore it back after calling CreateProcess.  If you insist I can do that.
-  I have changed gitattributes so that no automatic conversion of line-endings takes place when you commit.  For a full explanation of this see https://github.com/JAM-Software/Virtual-TreeView/issues/1151#issuecomment-1332032004.

**Comment by rickard67** [comment]
I've started to look at it and you've done a great job.

There are some issues though. I tried the demo using the TypeScript Language Server and encountered several errors.

E.g. To make Hover Request work i had to make some changes in JsonHoverResultToObject

`
function JsonHoverResultToObject(const ResultJson: TJSONValue): TLSPHoverResult;
var
  I: Integer;
  Contents: TJsonValue;
  Range,Start,&End: TJsonValue;
  Member: TJsonValue;
  JsonArray: TJSONArray;
begin
  Result := TLSPHoverResult.Create;

  if not (ResultJson is TJSONObject) then Exit;

  Range := ResultJson.FindValue('range');

  if Range is TJsonObject then
  begin
    Start := Range.FindValue('start');
    if Start is TJsonObject then
    begin
      // start { line: y, character: x }
      Result.range.start.line := Start.GetValue<Integer>('line', 0);
      Result.range.start.character := Start.GetValue<Integer>('character', 0);
    end;
    &End := Range.FindValue('end');
    if &end is TJsonObject then
    begin
      // end { line: y, character: x }
      Result.range.&end.line := &End.GetValue<Integer>('line', 0);
      Result.range.&end.character := &End.GetValue<Integer>('character', 0);
    end;
  end;

  Contents := ResultJson.FindValue('contents');

  if Contents is TJSONArray then
  begin
    // Result.contentsMarkedArray :=
    //  TSerializer.Deserialize<TArray<TLSPMarkedString>>(Contents);
    I := 0;
    JsonArray := TJsonArray(Contents);
    SetLength(Result.contentsMarkedArray, TJsonArray(JsonArray).Count);
    for Member in JsonArray do
    begin
      Result.contentsMarkedArray[I].language := Member.GetValue<string>('language','');
      Result.contentsMarkedArray[I].value := Member.GetValue<string>('value','');
      Inc(i);
    end;
  end
  else if Contents is TJSONObject then
  begin
    if Contents.GetValue<string>('language', '') <> '' then
      // MarkedString = language-value pair
      Result.MemberFromJsonValue('contentsMarked', Contents)
    else
      // MarkupContent
      Result.MemberFromJsonValue('contents', Contents);
  end
  else if Contents is TJSONString then
    // MarkedString = string
    Result.contents.value := TJSONString(Contents).value;
end;
`
I'm sure you can improve the code, but "Deserialize" doesn't seem to always work. If you can get "Deserialize" to work in the above code - that would be great. (The use of TSerializer.Deserialize scares me a little and may be prone to errors...)

There are other issues (errors) as well, but I haven't looked at them yet...

**Comment by rickard67** [comment]
Log: {"jsonrpc":"2.0","id":548,"result":{"contents":[{"language":"typescript","value":"(property) Cell.column: number"},""],"range":{"start":{"line":20,"character":40},"end":{"line":20,"character":46}}}}

Log: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/Rickard/Documents/Source/TypeScript/Samples/warship/warship.ts","diagnostics":[{"range":{"start":{"line":111,"character":25},"end":{"line":111,"character":30}},"message":"'event' is declared but its value is never read.","severity":4,"code":6133,"source":"typescript"},{"range":{"start":{"line":147,"character":24},"end":{"line":147,"character":27}},"message":"'evt' is declared but its value is never read.","severity":4,"code":6133,"source":"typescript"}]}}

**Comment by pyscripter** [comment]
Thanks. I will be having a look shortly.

**Comment by rickard67** [comment]
Some more data...

Log: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/Rickard/Documents/Source/TypeScript/Samples/warship/warship.ts","diagnostics":[{"range":{"start":{"line":111,"character":25},"end":{"line":111,"character":30}},"message":"'event' is declared but its value is never read.","severity":4,"code":6133,"source":"typescript"},{"range":{"start":{"line":147,"character":24},"end":{"line":147,"character":27}},"message":"'evt' is declared but its value is never read.","severity":4,"code":6133,"source":"typescript"}]}}

```pascal
// Publish diagnostics notification sent from the server.
  lspPublishDiagnostics:
    if Assigned(FOnPublishDiagnostics) then
    begin
      Params := TSmartPtr.Make(TLSPPublishDiagnosticsParams.Create)();
      Params.FromJSON(LJson.Values['params'] as TJSONObject);  <=== ERROR here

      FOnPublishDiagnostics(Self,
        TLSPPublishDiagnosticsParams(params).uri,
        TLSPPublishDiagnosticsParams(params).version,
        TLSPPublishDiagnosticsParams(params).diagnostics);
    end;

```

Log: {"jsonrpc":"2.0","id":1570,"result":[{"label":"cellLocation","kind":2,"sortText":"1","commitCharacters":[".",",","("],"data":{"file":"c:\\Users\\Rickard\\Documents\\Source\\TypeScript\\Samples\\warship\\warship.ts","line":21,"offset":41,"entryNames":["cellLocation"]},"insertTextFormat":2},{"label":"column","kind":5,"sortText":"1","commitCharacters":[".",",","("],"data":{"file":"c:\\Users\\Rickard\\Documents\\Source\\TypeScript\\Samples\\warship\\warship.ts","line":21,"offset":41,"entryNames":["column"]}},{"label":"element","kind":5,"sortText":"1","commitCharacters":[".",",","("],"data":{"file":"c:\\Users\\Rickard\\Documents\\Source\\TypeScript\\Samples\\warship\\warship.ts","line":21,"offset":41,"entryNames":["element"]}},{"label":"hasHit","kind":5,"sortText":"1","commitCharacters":[".",",","("],"data":{"file":"c:\\Users\\Rickard\\Documents\\Source\\TypeScript\\Samples\\warship\\warship.ts","line":21,"offset":41,"entryNames":["hasHit"]}},{"label":"row","kind":5,"sortText":"1","commitCharacters":[".",",","("],"data":{"file":"c:\\Users\\Rickard\\Documents\\Source\\TypeScript\\Samples\\warship\\warship.ts","line":21,"offset":41,"entryNames":["row"]}},{"label":"shipIndex","kind":5,"sortText":"1","commitCharacters":[".",",","("],"data":{"file":"c:\\Users\\Rickard\\Documents\\Source\\TypeScript\\Samples\\warship\\warship.ts","line":21,"offset":41,"entryNames":["shipIndex"]}}]}

```pascal
function JsonCompletionResultToObject(const ResultJson: TJSONValue): TLSPCompletionList;
begin
  Result := TLSPCompletionList.Create;

  if ResultJson is TJsonObject then
    Result.FromJSON(TJsonObject(ResultJson))
  else if ResultJson is TJsonArray then
    Result.MemberFromJsonValue('items', ResultJson); <=== ERROR here
end;
```

I think it would be easier if you installed the TypeScript language server yourself and gave it a try
https://www.rj-texted.se/Forum/viewtopic.php?t=5006

**Comment by pyscripter** [comment]
Strange.  I have tested publish diagnostics.  For instance

```pascal
procedure TForm1.LspOnPublishDiagnostics(Sender: TObject; const uri: string;
  const version: Cardinal; const diagnostics: TArray<TLSPDiagnostic>);
begin
  SynEdit2.Text := SynEdit2.Text + SLineBreak + TSerializer.Serialize(diagnostics);
end;
```

Log of response:

```json
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"E741","codeDescription":{"href":"https://docs.astral.sh/ruff/rules/ambiguous-variable-name"},"data":{"code":"E741","edits":[],"kind":{"body":"Ambiguous variable name: `l`","name":"AmbiguousVariableName","suggestion":null},"noqa_edit":{"newText":"  # noqa: E741\r\n","range":{"end":{"character":0,"line":24},"start":{"character":15,"line":23}}}},"message":"Ambiguous variable name: `l`","range":{"end":{"character":9,"line":23},"start":{"character":8,"line":23}},"severity":2,"source":"Ruff"},{"code":"E741","codeDescription":{"href":"https://docs.astral.sh/ruff/rules/ambiguous-variable-name"},"data":{"code":"E741","edits":[],"kind":{"body":"Ambiguous variable name: `l`","name":"AmbiguousVariableName","suggestion":null},"noqa_edit":{"newText":"  # noqa: E741\r\n","range":{"end":{"character":0,"line":21},"start":{"character":25,"line":20}}}},"message":"Ambiguous variable name: `l`","range":{"end":{"character":19,"line":20},"start":{"character":18,"line":20}},"severity":2,"source":"Ruff"},{"code":"E741","codeDescription":{"href":"https://docs.astral.sh/ruff/rules/ambiguous-variable-name"},"data":{"code":"E741","edits":[],"kind":{"body":"Ambiguous variable name: `l`","name":"AmbiguousVariableName","suggestion":null},"noqa_edit":{"newText":"  # noqa: E741\r\n","range":{"end":{"character":0,"line":23},"start":{"character":20,"line":22}}}},"message":"Ambiguous variable name: `l`","range":{"end":{"character":13,"line":22},"start":{"character":12,"line":22}},"severity":2,"source":"Ruff"}],"uri":"file:///c:/temp/python/module%201.py","version":0}
}
```

Output of the method:
```json
[{"range":{"start":{"line":23,"character":8},"end":{"line":23,"character":9}},"severity":2,"code":"E741","codeDescription":{"href":"https://docs.astral.sh/ruff/rules/ambiguous-variable-name"},"source":"Ruff","messageString":"","tags":[],"relatedInformation":[],"data":{"code":"E741","edits":[],"kind":{"body":"Ambiguous variable name: `l`","name":"AmbiguousVariableName","suggestion":null},"noqa_edit":{"newText":"  # noqa: E741\r\n","range":{"end":{"character":0,"line":24},"start":{"character":15,"line":23}}}}},{"range":{"start":{"line":20,"character":18},"end":{"line":20,"character":19}},"severity":2,"code":"E741","codeDescription":{"href":"https://docs.astral.sh/ruff/rules/ambiguous-variable-name"},"source":"Ruff","messageString":"","tags":[],"relatedInformation":[],"data":{"code":"E741","edits":[],"kind":{"body":"Ambiguous variable name: `l`","name":"AmbiguousVariableName","suggestion":null},"noqa_edit":{"newText":"  # noqa: E741\r\n","range":{"end":{"character":0,"line":21},"start":{"character":25,"line":20}}}}},{"range":{"start":{"line":22,"character":12},"end":{"line":22,"character":13}},"severity":2,"code":"E741","codeDescription":{"href":"https://docs.astral.sh/ruff/rules/ambiguous-variable-name"},"source":"Ruff","messageString":"","tags":[],"relatedInformation":[],"data":{"code":"E741","edits":[],"kind":{"body":"Ambiguous variable name: `l`","name":"AmbiguousVariableName","suggestion":null},"noqa_edit":{"newText":"  # noqa: E741\r\n","range":{"end":{"character":0,"line":23},"start":{"character":20,"line":22}}}}}
]
```

**Comment by pyscripter** [comment]
Aha!  Regarding the diagnostics, the code field is missing.

Can you add 

	/**
	 * The diagnostic's code, which might appear in the user interface.
	 */
        code: Variant;

to the definition of TLSPDiagnotic and try again?

**Comment by pyscripter** [comment]
Ok.  It is getting late here.   I will get back to you tomorrow.

**Comment by pyscripter** [comment]
A fix for the hover has been committed.  Please test and report.   
I will look into the diagnostics issue now.

**Comment by rickard67** [comment]
The content is retrieved properly now in JsonHoverResultToObject, but the range is not

```pascal
Result.MemberFromJsonValue('range', ResultJson.FindValue('ramge'));
```
range' is misspelled and changing it results in a new error when retrieving the range.

**Comment by pyscripter** [comment]
Oops.  Fixing the spelling works here:

```pascal
HoverRes = '''
{
    "contents": [
      {
        "language": "typescript",
        "value": "(property) Cell.column: number"
      },
      ""
    ],
    "range": {
      "start": {
        "line": 20,
        "character": 40
      },
      "end": {
        "line": 20,
        "character": 46
      }
    }
  }
''';
procedure TForm1.btnJsonClick(Sender: TObject);
var
  Res: TLSPHoverResult;
begin
  var JsonValue := TSmartPtr.Make(TJsonValue.ParseJSONValue(HoverRes))();
  Res := JsonHoverResultToObject(JsonValue);
  SynEdit2.Text := TSerializer.Serialize(Res);
  Res.Free;
```

Result: 

```json
{
  "contents": {
    "kind": "plaintext",
    "value": ""
  },
  "contentsMarked": {
    "language": "",
    "value": ""
  },
  "contentsMarkedArray": [
    {
      "language": "typescript",
      "value": "(property) Cell.column: number"
    },
    {
      "language": "",
      "value": ""
    }
  ],
  "range": {
    "start": {
      "line": 20,
      "character": 40
    },
    "end": {
      "line": 20,
      "character": 46
    }
  }
}
```

**Comment by rickard67** [comment]
I get an error on this line

```pascal
procedure TJSONObjectHelper.FromJSON(AJsonObject: TJSONObject);
...
  JsonSerializer.Populate(Reader, Self);

```
when calling

Result.MemberFromJsonValue('range', ResultJson.FindValue('range'));

**Comment by pyscripter** [comment]
Weird.   Can you try to sync the repo with my fork.  (I have just committed a fix + getting range in a different way.

Also can you try the code above?  Does it work on your side?  If not we need to figure out why.

**Comment by pyscripter** [comment]
I have tried the diagnostics:

```pascal
DiagnosticsRes = '''
 {
    "uri": "file:///C:/Users/Rickard/Documents/Source/TypeScript/Samples/warship/warship.ts",
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 111,
            "character": 25
          },
          "end": {
            "line": 111,
            "character": 30
          }
        },
        "message": "'event' is declared but its value is never read.",
        "severity": 4,
        "code": 6133,
        "source": "typescript"
      },
      {
        "range": {
          "start": {
            "line": 147,
            "character": 24
          },
          "end": {
            "line": 147,
            "character": 27
          }
        },
        "message": "'evt' is declared but its value is never read.",
        "severity": 4,
        "code": 6133,
        "source": "typescript"
      }
    ]
  }
 ''';
procedure TForm1.btnJsonClick(Sender: TObject);
begin
  var JsonValue := TSmartPtr.Make(TJsonValue.ParseJSONValue(DiagnosticsRes))();
  var Params := TSmartPtr.Make(TLSPPublishDiagnosticsParams.Create)();
  Params.FromJSON(JsonValue as TJSONObject);

  SynEdit2.Text := TSerializer.Serialize(Params);
```

and I get the following output:

```json
{
  "uri": "file:///C:/Users/Rickard/Documents/Source/TypeScript/Samples/warship/warship.ts",
  "version": 0,
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 111,
          "character": 25
        },
        "end": {
          "line": 111,
          "character": 30
        }
      },
      "severity": 4,
      "code": 6133,
      "codeDescription": {
        "href": ""
      },
      "source": "typescript",
      "messageString": "",
      "tags": [],
      "relatedInformation": [],
      "data": null
    },
    {
      "range": {
        "start": {
          "line": 147,
          "character": 24
        },
        "end": {
          "line": 147,
          "character": 27
        }
      },
      "severity": 4,
      "code": 6133,
      "codeDescription": {
        "href": ""
      },
      "source": "typescript",
      "messageString": "",
      "tags": [],
      "relatedInformation": [],
      "data": null
    }
  ]
}
```

So it works fine.   I wonder whether you use and older version of Delphi in which Serialization is buggy.   I can't explain it otherwise.

**Comment by pyscripter** [comment]
> I'm using Delphi 11.3.

I wonder whether this makes a difference.  I am on 12.3

**Comment by rickard67** [comment]
When trying the code with diagnostics I get the following exception

---------------------------
GExperts Debugger Exception Notification
---------------------------
Project LSPDemoProject.exe raised exception class EJsonSerializationException with message 'Unexpected token None'.
---------------------------
[&Filter ...] [Ignore &All this Session] [&Break] [Additional &Info] [&Continue]
---------------------------
ThreadId=10064
ProcessId=27
ThreadName=""
ExceptionMessage="Unexpected token None"
ExceptionName="EJsonSerializationException"
ExceptionDisplayName="EJsonSerializationException"
ExceptionAddress=767EDD22
FileName=<not available>
LineNumber=<not available>
ExceptionObject=033C4C40
Classes=[EJsonSerializationException,Exception,TObject]

---------------------------

**Comment by pyscripter** [comment]
I happen to have Delphi 11 installed.  I will try and see whether this explains the issue and maybe find a work around.

**Comment by pyscripter** [comment]
As I guessed, it fails on Delphi 11.   I will see whether there is a work around.  Big shame, because avoiding by hand serialization makes life much easier.

**Comment by pyscripter** [comment]
Commited a fix for Delphi 11 and earlier.  It was failing to deserialize any integer field when deserializing from TJSONValue.  

Now the following and I suppose much more works  in my Delphi 11:

DiagnosticsRes =
'{'#13#10 + //0
'  "uri": "file:///C:/Users/Rickard/Documents/Source/TypeScript/Samples/warship/warship.ts",'#13#10 + //1
'  "version": 0,'#13#10 + //2
'  "diagnostics": ['#13#10 + //3
'    {'#13#10 + //4
'      "range": {'#13#10 + //5
'        "start": {'#13#10 + //6
'          "line": 111,'#13#10 + //7
'          "character": 25'#13#10 + //8
'        },'#13#10 + //9
'        "end": {'#13#10 + //10
'          "line": 111,'#13#10 + //11
'          "character": 30'#13#10 + //12
'        }'#13#10 + //13
'      },'#13#10 + //14
'      "severity": 4,'#13#10 + //15
'      "code": 6133,'#13#10 + //16
'      "codeDescription": {'#13#10 + //17
'        "href": ""'#13#10 + //18
'      },'#13#10 + //19
'      "source": "typescript",'#13#10 + //20
'      "messageString": "",'#13#10 + //21
'      "tags": [],'#13#10 + //22
'      "relatedInformation": [],'#13#10 + //23
'      "data": null'#13#10 + //24
'    },'#13#10 + //25
'    {'#13#10 + //26
'      "range": {'#13#10 + //27
'        "start": {'#13#10 + //28
'          "line": 147,'#13#10 + //29
'          "character": 24'#13#10 + //30
'        },'#13#10 + //31
'        "end": {'#13#10 + //32
'          "line": 147,'#13#10 + //33
'          "character": 27'#13#10 + //34
'        }'#13#10 + //35
'      },'#13#10 + //36
'      "severity": 4,'#13#10 + //37
'      "code": 6133,'#13#10 + //38
'      "codeDescription": {'#13#10 + //39
'        "href": ""'#13#10 + //40
'      },'#13#10 + //41
'      "source": "typescript",'#13#10 + //42
'      "messageString": "",'#13#10 + //43
'      "tags": [],'#13#10 + //44
'      "relatedInformation": [],'#13#10 + //45
'      "data": null'#13#10 + //46
'    }'#13#10 + //47
'  ]'#13#10 + //48
'}'#13#10  //49
;


procedure TForm1.btnJsonClick(Sender: TObject);
begin
  var Range := TSmartPtr.Make(TSerializer.Deserialize<TLSPPublishDiagnosticsParams>(DiagnosticsRes))();

  SynEdit2.Text := TSerializer.Serialize(Range);

Could you please test?

**Comment by rickard67** [comment]
Tested the latest committed code and it works much better now. No issues with diagnostics, hover and completion requests.

I'll start testing in earnest later today. I noticed I need to make some improvements to the demo as well. 

I have Delphi 10.4 installed in a virtual machine, I'll try using that as well...

Thanks for your hard work :)

**Comment by rickard67** [comment]
BTW. I think we could use a second demo implementing handling of server responses with anonymous methods. Also, some explanation to why and how to use them.

Sending a request and handle the response in an event makes much more sense to me... but I could be wrong.

**Comment by pyscripter** [comment]
One thing I want to change, but I waited to ask you first is the order of parameters in SendRequest:

```pascal
function TLSPClient.SendRequest(const lspKind: TLSPKind;
  const method: string = ''; params: TLSPBaseParams = nil;
  const paramJSON: string = ''): Integer;
```

method is almost never used and params is almost always used.   I would like to change the order of parameters, so that you don't have to include and empty string.  What do you think?

**Comment by pyscripter** [comment]
> `Params := TSmartPtr.Make(TLSPDidChangeTextDocumentParams.Create)();`
> 
> Maybe something like
> 
> `Params := FLSPClient.CreateParamObject(TLSPDidChangeTextDocumentParams);`

Is that simpler? More text.

Users don't have to use smart pointers.  They can always use

```pascal
Params := TLSPDidChangeTextDocumentParams.Create;
try

finally
  Params.Free;
end;

```

And If they do use TSmartPtr, they better understand the purpose it serves.

**Comment by pyscripter** [comment]
> I would like to keep things as backwards compatible as possible. Maybe you could create overload functions?

Committed a simpler SendRequest overload.

**Comment by pyscripter** [comment]
Fixed.

**Comment by rickard67** [comment]
It is now working in RJ TextEd. I've tested most requests and notifications the editor is capable of, but still only using the TypeScript Language Server. So still have ways to go...

1. I had to change an event in XLSPClient.pas to be able to set item.resolved := true;
`
TOnCompletionItemResolveEvent = procedure(Sender: TObject; const Id: Integer; item: TLSPCompletionItem) of object;
`
2. Added a new method to XLSPClient. SendNotification() - which just call NotifyServer(). Using SendRequest() and SendNotification() feels more intuitive.

3. I think we should have some documentation on how to move to the new version. I have a draft:



**Move to this new version**
This is a new version of the component with many code changes. If you use the old implementation you will have to make several changes in order to use this new version.
Many features still work basically the same.

**Events**
Most events are defined with different arguments in the new version. You can find all declared events in XLSPClient.pas.

E.g.

    TOnCodeActionResolveEvent = procedure(Sender: TObject; const value: TLSPCodeAction; const errorCode: Integer; const errorMessage: string) of object;

is now declared as

    TOnCodeActionResolveEvent = procedure(Sender: TObject; const Id: Integer; const value: TLSPCodeActionResolveResult) of object;

Id is an unique number to identify the request made to the server (in case you made several requests).
TLSPCodeAction has changed to TLSPCodeActionResolveResult and errorCode and errorMessage has been removed.


**Values**
Some values have changed name.

    .slabel         =>   .&label
    .startPos       =>   .start
    .endPos         =>   .&end
    .messageString  =>   .&message

E.g.
    startx := LRange.start.character;
    starty := LRange.start.line;
    endx := LRange.&end.character;
    endy := LRange.&end.line;


**Notifications**
Notifications are not sent using SendRequest() anymore. Use SendNotification() or NotifyServer().

This means you have to change the function call for the following server calls:

LSPClientNotifications: set of TLSPKind = [
    lspInitialized, lspExit, lspWorkDoneProgressCancel,
    lspDidOpenTextDocument, lspDidChangeTextDocument,
    lspDidSaveTextDocument, lspDidCloseTextDocument,
    lspWillSaveTextDocument, lspDidChangeWatchedFiles,
    lspDidOpenNotebookDocument, lspDidChangeNotebookDocument,
    lspDidSaveNotebookDocument, lspDidCloseNotebookDocument,
    lspDidChangeWorkspaceFolders, lspDidChangeConfiguration,
    lspWorkspaceDidCreateFiles, lspWorkspaceDidRenameFiles,
    lspWorkspaceDidDeleteFiles, lspSetTrace
  ];

**Comment by pyscripter** [comment]
Renamed NotifyServer to SendNotification
Set completionItem.resolved to True, when processing the completionItemResolve response.

**Comment by rickard67** [comment]
Thanks :)

I tried this in OnCompletionItemResolve() and it works fine.

  if TLSPMarkupContent.FromJsonRaw(item.documentation).kind = TLSPMarkupKind.markdown then
    S := TLSPMarkupContent.FromJsonRaw(item.documentation).value
  else
    S := Item.documentation;

If we don't change anything, it needs to be documented in ReadMe.md. But if you feel up to it, a custom converter for TLSPMarkupContent would be nice (and probably more intuitive than converting Json strings...

**Comment by pyscripter** [comment]
> if TLSPMarkupContent.FromJsonRaw(item.documentation).kind = TLSPMarkupKind.markdown then
> S := TLSPMarkupContent.FromJsonRaw(item.documentation).value
> else
> S := Item.documentation;

You don't need that.  Simply:

`S := TLSPMarkupContent.FromJsonRaw(item.documentation).value`

**Comment by rickard67** [comment]
Ah, that's cool :)

**Comment by pyscripter** [comment]
Could you post here a list of requests that have tested?   It would be useful for me to know.

**Comment by rickard67** [comment]
Language servers support different requests but I've tested these with the TypeScript server:

CodeActionRequest
CompletionRequest
CompletionResolveRequest
DidChangeTextDocument
DidCloseTextDocument
DidOpenTextDocument
DidSaveTextDocument
DocumentHighlight

DocumentSymbol => returnes Json code so it doesn't work at the moment (TLSPDocumentSymbolsResult)

References
GotoDeclaration
GotoDefinition
GotoImplementation
GotoTypeDefinition
Hover
Rename

**Comment by pyscripter** [comment]
Change:

```pascal
  TLSPSymbolKind = (
    symFile=1,symModule,symNamespace,symPackage,symClass,symMethod,symProperty,symField,
    symConstructor,symEnum,symInterface,symFunction,symVariable,symConstant,symString,
    symNumber,symBoolean,symArray,symObject,symKey,symNull,symEnumMember,symStruct,
    symEvent,symOperator,symTypeParameter
  );
```
to
  TLSPSymbolKind = (
    synUnknown, symFile,symModule,symNamespace,symPackage,symClass,symMethod,symProperty,symField,
    symConstructor,symEnum,symInterface,symFunction,symVariable,symConstant,symString,
    symNumber,symBoolean,symArray,symObject,symKey,symNull,symEnumMember,symStruct,
    symEvent,symOperator,symTypeParameter
  );

Does this help?

**Comment by rickard67** [comment]
Well, not really. kind is now always symUnknown.

**Comment by rickard67** [comment]
I didn't say it was wrong! It just lack that elegance :)
I'm honestly fine with it.

I did a quick search, does any of these pose a problem

TLSPSemanticTokenType = (semtokenFullFalse, semtokenFull , semtokenDelta);
TLSPMessageType = (lspMsgError=1, lspMsgWarning, lspMsgInfo, lspMsgLog);

I haven't checked, just made a search...

**Comment by rickard67** [comment]
Changed 

TLSPDocumentSymbolParams = class(TLSPPartialResultParams)
  kind: Integer;

and added a few TLSPSymbolKind(kind) in my code. It works just fine...

I'll test a few more requests tomorrow and try with more language servers.

**Comment by pyscripter** [comment]
> WorkspaceSymbol <= Fixed. Change in XLSPClient to:

Committed the change.

**Comment by rickard67** [comment]
Tested a few more language servers. All worked fine until I tried the Fortran language server.

TypeScript Language Server
PHP Intelephense
Python Language Server
clangd language server
Rust Language Server
Fortran

1. The Fortran language server complains if an url only consist of "file:". It want's empty urls to be "file:///".

Made a quick fix in XLSPFunctions

function FilePathToUri(APath: string): string;
const
  // The use of this flag in UrlCreateFromPath is undocumented.
  // It is used in URLEscape.  Its use fixes #1346.
  URL_ESCAPE_AS_UTF8: DWORD = $00040000;
begin
  var BufferLen: DWORD := INTERNET_MAX_URL_LENGTH;
  if APath = '' then APath := '\';
  SetLength(Result, BufferLen);
  OleCheck(UrlCreateFromPath(PChar(APath), PChar(Result), @BufferLen, URL_ESCAPE_AS_UTF8));
  SetLength(Result, BufferLen);
end;

Seems to work fine after the change...


2. Be able to log requests and notification sent to the server can be very helpful. I'm missing

  procedure TLSPClient.SendToServer(const AJson: string);
  ...
  if FLogToFile and FLogCommunication and (AJson <> '') then
    SaveToLogFile('Write to server:' + #13#10 + AJson);

**Comment by pyscripter** [comment]
Let me respond first about logging.  Happy to add the ability to log messages sent to server.

We could define an enumeration:
```pascal
TLogItem = (liServerMessages, liClientMessages);
TLogItems = set of TLogItem;
```

if we want finer control then:
TLogItem = (liClientRequests, liClientNotifications, , liClientResponses, liServerRequests, liServerNotifications, IServerResponses);

and  the process the option appropriately.   I think the first option should be enough.

Regarding empty file:\\,  What are you using it for?  Is this for unsaved buffers?  Not a good idea, since you may have many unsaved buffers.   Then how can you tell which is which?

What is VsCode is using for unsaved buffers is a different scheme "untitled:buffername".   LSP servers are meant to leave it untouched, but not all servers support unknown URI schemes (see https://github.com/openlawlibrary/pygls/issues/209).  What I ended up using in PyScripter is a hack:


```pascal
function FileIdToURI(const FilePath: string): string;
var

begin
  ..
  else
    // Not sure how to handle unsaved files
    // and used the following workaround
    Result := 'file://untitled/temp/'+ FilePath;
end;

function FileIdFromURI(const URI: string): string;
begin
  if URI.StartsWith('file://untitled/temp/') then
  begin
    ..
end;
```

**Comment by rickard67** [comment]
```pascal
TLogItem = (liServerMessages, liClientMessages);
TLogItems = set of TLogItem;
```
This should be enough.

About empty paths:
E.g. in OnInitialize() I set the path/URI by calling  

```
    // Set root
    value.AddRoot(s);
```
It may be a valid path, or an empty string. If it's empty the LSP Client will send a request seen below

`
{"jsonrpc": "2.0","id": 256,"method": "initialize","params": {"processId":13288,"clientInfo":{"name":"Pascal LSP Client","version":"1.0"},"locale":"","rootUri":"file:","capabilities":{
`
were we get "rootUri":"file:". The fix just make sure that doesn't ever happen and we get
"rootUri":"file:\/\/\/"  (file:///) instead.

We could also add a check in AddRoot(const sz: string)

e.g.

```pascal
  if s <> '' then
  begin
    rootPath := sz;
    rootUri := FilePathToUri(sz);
  end;
```

**Comment by rickard67** [comment]
```pascal
function FilePathToUri(const APath: string): string;
const
  // The use of this flag in UrlCreateFromPath is undocumented.
  // It is used in URLEscape.  Its use fixes #1346.
  URL_ESCAPE_AS_UTF8: DWORD = $00040000;
begin
  if APath = '' then Exit;
  
  var BufferLen: DWORD := INTERNET_MAX_URL_LENGTH;
  SetLength(Result, BufferLen);
  OleCheck(UrlCreateFromPath(PChar(APath), PChar(Result), @BufferLen, URL_ESCAPE_AS_UTF8));
  SetLength(Result, BufferLen);
end;
```

Maybe a better solution?

**Comment by pyscripter** [comment]
> The client is supposed to work as the server and listen for a connection on the specified port and the language server should be started up to connect to the same port.

NO! It is the other way round.  I have used successfully with a [pygls ](https://github.com/openlawlibrary/pygls)server which is used by [quite a few servers](https://github.com/openlawlibrary/pygls/blob/main/Implementations.md).

**Comment by pyscripter** [comment]
The servers I mentioned act only as TCP servers, not clients.  I will do some more research.  It doesn't feel right that it is up to the client to decide

**Comment by rickard67** [comment]
We can add vscode-css-languageserver to the list of tested servers.

It works fine using stdio :) Since it support socket communication I just had to try and got

---------------------------
GExperts Debugger Exception Notification
---------------------------
Project TextEd.exe raised exception class ESocketError with message 'Network socket error: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det (10061), on API 'connect''.
---------------------------
[&Filter ...] [Ignore &All this Session] [&Break] [Additional &Info] [&Continue]
---------------------------
ThreadId=5016
ProcessId=15
ThreadName=""
ExceptionMessage="Network socket error: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det (10061), on API 'connect'"
ExceptionName="ESocketError"
ExceptionDisplayName="ESocketError"
ExceptionAddress=75A6DD42
FileName=<not available>
LineNumber=<not available>
ExceptionObject=117FAB18
Classes=[ESocketError,Exception,TObject]

---------------------------

My old implementation acting as a server works fine (it won't work as a client though...).

From a user perspective it could be implement as radio buttons (or something)

```
--- Communication channel ------
    - Standard input output (stdio)
    - Socket as a TCP server
    - Socket as a TCP client
```

I don't really see it as an issue, letting the user make that decision.

**Comment by pyscripter** [comment]
Introduced 

```pascal
  TLspLogItem = (liServerRPCMessages, liClientRPCMessages, liServerMessages); 
  TLspLogItems = set of TLspLogItem;
```

and removed LogCommunication, LogServerMessages (corresponds to liServerMessages);

SendToServer does logs the json if liClientRPCMessages is set.

We could also remove LogToFile and control everything via  LogItems.   What do you thing?

**Comment by pyscripter** [comment]
Removed LogToFile (does not log anything if FLogItems = [])
Simplified SaveToLogFile preserving the UTF8 encoding.  Removed FFileLog and FFileLogList.

**Comment by rickard67** [comment]
```pascal
procedure TLSPExecuteServerThread.ProcessErrorOutput(Bytes: TBytes);
begin
  if Assigned(FOnReadErrorFromServer) then
  begin
    if IsUTF8String(RawByteString(Bytes)) then
      FOnReadErrorFromServer(Self, TEncoding.UTF8.GetString(Bytes))
    else
      FOnReadErrorFromServer(Self, TEncoding.ANSI.GetString(Bytes));
  end;
end;
```

works better...

**Comment by pyscripter** [comment]
I am thinking of adding to TLSPExecuteServerThread a OnServerConnected event.   The client will hook this event and call SendRequest(lspInitialize) so that the user does not need to do that.

What do you think?

**Comment by rickard67** [comment]
TEncoding.UTF8.IsBufferValid(Bytes) doesn't exist in Delphi 11.3.

I was able to run the Typescript language server with TTransportType.ttSocketServer.

The server still restarts when closing it. Removing 

`FRestartServer := lspKind <> lspInitialize;`

in SendRequest() and adding FRestartServer in OnResponseTimer() seems to work.

```pascal
procedure TLSPClient.OnResponseTimer(Sender: TObject);
begin
  FResponseTimer.Enabled := False;
  FCloseTimer.Enabled := False;
  FExitTimer.Enabled := False;
  if Assigned(FServerThread) then
  begin
    // The server doesn't seem to have responded to requests.
    // Terminate the thread.
    FRestartServer := True;
    FServerThread.Terminate;
  end;
end;
```

The python-lsp-server still crashes every time it's closed. I'll lock at it more when I get the time...

If you intend to add LSP capability and read some documentation - I think you expect to send an Initialize request to the server. It may be confusing if the client does that for you(?)

**Comment by pyscripter** [comment]
> If you, as a user, intend to add LSP capability and have read some documentation - I think you expect to send an Initialize request to the server. It may be confusing if the client does that for you(?)

Agree.    I will add the event to the Client, so the user can use it to send the request lspInitialize.

**Comment by rickard67** [comment]
[python-lsp-server](https://github.com/python-lsp/python-lsp-server)

**Comment by pyscripter** [comment]
> in SendRequest() and adding FRestartServer in OnResponseTimer() seems to work.

It works because this method is not triggered when you SendRequest(lspShutdown).  If for some reason it does , then the Server will restart.

I committed a different fix: 

FRestartServer := not (lspKind in [lspInitialize, lspShutdown, lspExit]);

in SendRequest.

**Comment by rickard67** [comment]
I've tested OnConnected() and it works nicely. The FRestartServer fix as well. 
Still getting nasty crashes when using python-lsp-server. You may have to start and close it a couple of times.

The error message isn't that helpful and neither is the callstack:

```
ThreadId=7148
ProcessId=3
ThreadName=""
ExceptionMessage="Access violation at address C000014B. Execution of address C000014B"
ExceptionName="EAccessViolation"
ExceptionDisplayName="$C0000005"
ExceptionAddress=C000014B
FileName=<not available>
LineNumber=<not available>
```

```
WaitForSyncWaitObj + $7
MonitorEnter + $4
TThread.Synchronize + $46
TThread.Synchronize + $E
TThread.DoTerminate + $12
```

I haven't had time to investigate, but wanted you to know the latest commit works fine (except with the python-lsp-server).

**Comment by rickard67** [comment]
I'll check when I get the time. I do suspect that the server keeps sending data after the shutdown request and before the exit notification has been sent...

**Comment by rickard67** [comment]
```pascal
// Completion routine for ReadFileEx
procedure ReadCompletionRoutine(dwErrorCode: DWORD; dwNumberOfBytesTransfered: DWORD;
  lpOverlapped: POverlapped); stdcall;
begin
  // Check for errors or pipe closure
  if dwErrorCode <> 0 then Exit;

  // Process received data
```

This seems to work fine. Do we really need to terminate if we get dwErrorCode <> 0 ?

**Comment by rickard67** [comment]
> Is it because it happens after the thread is destroyed?
I'm guessing no, since a simple function call before the terminate call helps.

Adding OutputDebugString(PChar('dwErrorCode <> 0')); before the terminate call works like the sleep() call and fix the problem :)

```pascal
// Completion routine for ReadFileEx
procedure ReadCompletionRoutine(dwErrorCode: DWORD; dwNumberOfBytesTransfered: DWORD;
  lpOverlapped: POverlapped); stdcall;
begin
  // Check for errors or pipe closure
  if dwErrorCode <> 0 then
  begin
    if not PExtOverlapped(lpOverlapped).ServerThread.Terminated then
    begin
      OutputDebugString(PChar('dwErrorCode <> 0'));
      PExtOverlapped(lpOverlapped).ServerThread.Terminate;
    end;
    Exit;
  end;
```

**Comment by pyscripter** [comment]
Amazing.  Still unclear why the error happens, but maybe we can leave it there (adding an OutputDebugString call) and revisit it if the error resurfaces.

**Comment by rickard67** [comment]
I noticed you made some changes inside TLSPClient.SaveToLogFile()

Unfortunately, it makes the log file almost unreadable. We need a few line breaks between requests and responses.

This works:

```pascal
procedure TLSPClient.SaveToLogFile(const w: string);
var
  FileStream: TFileStream;
  Bytes: TBytes;
begin
  if FLogFileName = '' then Exit;

  if not FileExists(FLogFileName) then
    FileStream := TFileStream.Create(FLogFileName, fmCreate)
  else
    FileStream := TFileStream.Create(FLogFileName, fmOpenReadWrite);
  try
    FileStream.Seek(0, soEnd);
    Bytes := TEncoding.UTF8.GetBytes(#13#10+w+#13#10);
    FileStream.Write(Bytes, Length(Bytes));
  finally
    FileStream.Free;
  end;
end; 
```

**Comment by rickard67** [comment]
Also, XLSPFunctions.FilePathToURI() still returns "file:" if APath is an empty string.

This works:

```pascal
function FilePathToURI(const APath: string): string;
const
  // The use of this flag in UrlCreateFromPath is undocumented.
  // It is used in URLEscape.  Its use fixes #1346.
  URL_ESCAPE_AS_UTF8: DWORD = $00040000;
begin
  if APath = '' then Exit;
  var BufferLen: DWORD := INTERNET_MAX_URL_LENGTH;
  SetLength(Result, BufferLen);
  OleCheck(UrlCreateFromPath(PChar(APath), PChar(Result), @BufferLen, URL_ESCAPE_AS_UTF8));
  SetLength(Result, BufferLen);
end;
```

**Comment by rickard67** [comment]
I changed:

```pascal
[JsonIgnore]
location: TLSPLocation; // location: Location | { uri: DocumentUri };
```

and

```pascal
function JsonWorkspaceSymbolResultToObject(const ResultJson: TJSONValue): TLSPWorkspaceSymbolInformationResult;
var
  ContentsArray: TJsonArray;
  ContentObject: TJsonObject;
  Content: TJsonValue;
  Index: Integer;
begin
  Result := TLSPWorkspaceSymbolInformationResult.Create;
  if ResultJson is TJSONArray then
  begin
    ContentsArray := TJSONArray(ResultJson);
    Result.MemberFromJsonValue('values', ResultJson);

    for Index := 0 to Min(ContentsArray.Count,Length(Result.values)) - 1 do // Min() in case something went wrong with serialization
    begin
      if ContentsArray[Index] is TJsonObject then
      begin
        Content := ContentsArray[Index].FindValue('location');
        if Content is TJsonObject then
        begin
          if Content.FindValue('uri') is TJsonString then
          begin
            // location = { uri: string }
            Result.values[Index].location.uri := Content.FindValue('uri').Value;
          end
          else
          begin
            // location = TLSPLocation
            Result.values[Index].location := TSerializer.Deserialize<TLSPLocation>(Content.Value);
          end;
        end;
      end;
    end;
  end;
end;
```

Does it look okey?

**Comment by pyscripter** [comment]
location: Location | { uri: DocumentUri };

interface Location {
	uri: DocumentUri;
	range: Range;
}

Why do you need manual deserialization.  In both cases the object would contain uri.  It is just the range that might be missing?

**Comment by rickard67** [comment]
It seems to work. Thanks.

**Comment by rickard67** [comment]
I think I would like a similar solution for TLSPMarkupContent (and TLSPRelativePattern) in e.g.
TLSPCompletionItem.

TLSPCompletionItem = record

  function GetDocumentationAsString: string;
  function GetDocumentationAsMarkupContent: TLSPMarkupContent;

**Comment by rickard67** [comment]
Maybe even add properties(?)

```pascal
  function GetLabelAsString: string;
  function GetLabelAsArray: TArray<TLSPInlayHintLabelPart>;
  property LabelAsString: string read GetLabelAsString;
  property LabelAsArray: TArray<TLSPInlayHintLabelPart> read GetLabelAsArray;
```

**Comment by rickard67** [comment]
BTW. could we use something like

```pascal
TLSPJsonString = string;

TLSPInlayHint = record
  [JsonConverter(TJsonRawConverter)]
  &label: TLSPJsonString;  // label: string | InlayHintLabelPart[];
```

It would make it easier to see what "label" contains. And with properties much more intuitive...

**Comment by pyscripter** [comment]
> I think I would like a similar solution for TLSPMarkupContent (and TLSPRelativePattern) in e.g. TLSPCompletionItem.
> 
> TLSPCompletionItem = record
> 
>   function GetDocumentationAsString: string;
>   function GetDocumentationAsMarkupContent: TLSPMarkupContent;

There is a difference.  If contents contains a plain string, it is converted to TLSPMarkupContent, so you do not need to check.  You just use the MarkupContent in all cases which is much simpler.

Here a string and an array of Parts are totally incompatible and you will have to check:
```pascal
if GetLabelAsString = '' then
   // do somthing
else
  GetLabelasArray // and do something.
```

Happy to make them properties if you prefer, but you would have to add JSONIgnore.  I don't think the benefit is worth it, but happy to oblige if you insist.

**Comment by rickard67** [comment]
I just feel that from a user perspective - this is simpler to use

```pascal
  s := item.documentationMarkup.value;
```

if we set

```pascal
  function GetDocumentationMarkup: TLSPMarkupContent;
  [JsonIgnore]
  property documentationMarkup: TLSPMarkupContent read GetDocumentationMarkup;
```

rather than

`
s := := TLSPMarkupContent.FromJsonRaw(item.documentation).value;
`

Also, it would be nice if we could somehow hide "documentation" from the user and only display documentationMarkup.

Maybe

```pascal
  private
    // A human-readable string that represents a doc-comment.
    // string | MarkupContent
    [JsonConverter(TJsonRawConverter)]
    documentation: string;
```

Or is it too much(?)...

**Comment by rickard67** [comment]
I'm still not sure, but...
If it's okey, I would like to merge most of it. I want to keep, and do my own documentation. I made some updates to the ReadMe.md (some are taken from your version). 
And I want more documentation on how to migrate to the new version.

There are some things I would like to do. But if we are both actively adding and changing the code (or demo), it may become complicated. 
So it depends on what you want to do as well. Do you want to keep your own separate fork, or do you feel there should only be one main fork everyone adds to?

I still want to keep the x-superobject version around in a subfolder (since it works with earlier Delphi versions). 
I've added some code from the new XLSPExecute unit, made some changes to it, and it works. So the x-superobject version now uses asynchronous communication, and can use communicate over a socket as either server or client.

**Comment by rickard67** [comment]
I felt it was just easier to erase everything and commit a new version of everything...

**Comment by pyscripter** [comment]
> I felt it was just easier to erase everything and commit a new version of everything...

You lose your history and my history that way.  You should create a branch to start with to save existing stuff and then
 merge a PR from my fork

**Comment by rickard67** [comment]
Already reverted, pulled changes from the fork and committed new changes :)

**Comment by pyscripter** [comment]
Added a PR with the MIT license added.

I am now closing this issue.
